name: Your Workflow

on:
  push:
    branches:
      - dev

env:
  BUILD_NUMBER: ${{ github.run_number }}
  BRANCH_NAME: ${{ github.ref_name }} #${{ github.head_ref || github.ref_name }} 
jobs:
  build:
    runs-on: windows-latest

    steps:
     - name: Set Date
       id: version
       run: |
          $dateString = Get-Date -Format "yyyy.MM.dd"
          echo "version=$dateString.${{ env.BUILD_NUMBER }}" >> $GITHUB_ENV
       env:
          GITHUB_ENV: env.list

     - name: Use Date
       run: |
          echo "Version: ${{ env.version }}"

     - name: Use Date, Build Number, and Branch Name
       run: |
          echo "${{ env.BRANCH_NAME }}_${{ env.BUILD_NUMBER }}"
