name: Your Workflow

on:
  push:
    branches:
      - dev

env:
  BUILD_NUMBER: ${{ github.run_number }}
  BRANCH_NAME: ${{ github.ref_name }} #${{ github.head_ref || github.ref_name }} 
jobs:
  build:
    runs-on: windows-latest

    steps:
     - name: "Set current date as env variable"
       run: |
          echo "dateString=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
       id: version  # this is used on variable path

      # Your other steps in the workflow that use the environment variables
      # ...

     - name: Use Date, Build Number, and Branch Name
       run: |
          echo "${{ env.BRANCH_NAME }}_${{ env.BUILD_NUMBER }}"
          echo "${{ env.DEBUG }}"
       shell: pwsh
       env:
          DEBUG: ${{ steps.version.outputs.builddate }}-DEBUG
