name: Your Workflow

on:
  push:
    branches:
      - dev

env:
  BUILD_NUMBER: ${{ github.run_number }}
  BRANCH_NAME: ${{ github.ref_name }} #${{ github.head_ref || github.ref_name }} 
jobs:
  build:
    runs-on: windows-latest

    steps:
     - name: Set Version
       run: echo "version=1.0.0" >> $GITHUB_ENV
       
     - name: Use Version
       run: |
          echo "Version: ${{ env.VERSION }}"

     - name: Use Date, Build Number, and Branch Name
       run: |
          echo "${{ env.BRANCH_NAME }}_${{ env.BUILD_NUMBER }}"
