name: Your Workflow

on:
  push:
    branches:
      - dev

env:
  BUILD_NUMBER: ${{ github.run_number }}
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set Version
        run: |
          echo "DATE_STRING=$(Get-Date -Format 'yyyy.MM.dd')" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        env:
          GITHUB_ENV: env.list   

      # Your other steps in the workflow that use the environment variables
      # ...

      - name: Use Date, Build Number, and Branch Name
        run: |
          echo "Date: $env:DATE_STRING"
          echo "Build Number: $env:BUILD_NUMBER"
          echo "Branch Name: $env:BRANCH_NAME"
        shell: pwsh
