name: Your Workflow

on:
  push:
    branches:
      - dev

env:
  BUILD_NUMBER: ${{ github.run_number }}
  BRANCH_NAME: ${{ github.ref_name }} #${{ github.head_ref || github.ref_name }} 
jobs:
  build:
    runs-on: windows-latest

    steps:
     - name: Set Date
       run: |
          $dateString = Get-Date -Format "yyyy.MM.dd"
          echo "dateString=$dateString"
          echo "::set-env name=DATE_STRING::$dateString"

     - name: Use Date
       run: |
          echo "Date: ${{ env.DATE_STRING }}"

     - name: Use Date, Build Number, and Branch Name
       run: |
          echo "${{ env.BRANCH_NAME }}_${{ env.BUILD_NUMBER }}"
