name: Your Workflow

on:
  push:
    branches:
      - dev

env:
  BUILD_NUMBER: ${{ github.run_number }}
  BRANCH_NAME: ${{ github.ref_name }} #${{ github.head_ref || github.ref_name }} 
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set Version
        run: |
          echo "currentDT=$(date +'%Y-%m-%dZ%H-%M-%S')" >> $GITHUB_ENV
        env:
          GITHUB_ENV: env.list   

      # Your other steps in the workflow that use the environment variables
      # ...

      - name: Use Date, Build Number, and Branch Name
        run: |
          echo "${{ env.BRANCH_NAME }}_${{ env.BUILD_NUMBER }}"
          echo "${{ env.currentDT }}"
        shell: pwsh
