name: Your Workflow

on:
  push:
    branches:
      - dev

env:
  BUILD_NUMBER: ${{ github.run_number }}
  BRANCH_NAME: ${{ github.ref_name }} #${{ github.head_ref || github.ref_name }} 
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Get current date
        id: date
        run: |
          dateString=$(date +'%Y-%m-%d')
          echo "date=$dateString"
          echo "date=$dateString" >> $GITHUB_ENV
          echo "date=$dateString" >> $GITHUB_OUTPUT
        
      - name: Test with environment variables
        run: echo "${{ env.RELEASE_NAME }}"
        env:
          TAG_NAME: nightly-tag-${{ steps.date.outputs.dateString }}
          RELEASE_NAME: nightly-release-${{ steps.date.outputs.dateString }}
